//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.02 at 02:58:26 PM NZDT 
//


package openadr.model.v20b.ei;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import openadr.model.v20b.OadrCreateOpt;
import openadr.model.v20b.emix.MarketContext;
import openadr.model.v20b.xcal.DateTime;
import openadr.model.v20b.xcal.Vavailability;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Opts are used by the VEN to temporarily override the pre-existing agreement. For example, a VEN may opt in to events during the evening, or opt out from events during the world series.
 * 
 * <p>Java class for EiOptType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EiOptType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}optID"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}optType"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}optReason"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/emix/2011/06}marketContext" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}venID"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:icalendar-2.0}vavailability" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}createdDateTime"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://docs.oasis-open.org/ns/energyinterop/201110}schemaVersion"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EiOptType", propOrder = {
    "optID",
    "optType",
    "optReason",
    "marketContext",
    "venID",
    "vavailability",
    "createdDateTime"
})
@XmlSeeAlso({
    OadrCreateOpt.class
})
public class EiOptType implements Serializable, Equals2, HashCode2, ToString2
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String optID;
    @XmlElement(required = true)
    protected OptTypeType optType;
    @XmlElement(required = true)
    protected String optReason;
    @XmlElement(namespace = "http://docs.oasis-open.org/ns/emix/2011/06")
    protected MarketContext marketContext;
    @XmlElement(required = true)
    protected String venID;
    @XmlElement(namespace = "urn:ietf:params:xml:ns:icalendar-2.0")
    protected Vavailability vavailability;
    @XmlElement(required = true)
    protected DateTime createdDateTime;
    @XmlAttribute(name = "schemaVersion", namespace = "http://docs.oasis-open.org/ns/energyinterop/201110")
    protected String schemaVersion;

    /**
     * Default no-arg constructor
     * 
     */
    public EiOptType() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public EiOptType(final String optID, final OptTypeType optType, final String optReason, final MarketContext marketContext, final String venID, final Vavailability vavailability, final DateTime createdDateTime, final String schemaVersion) {
        this.optID = optID;
        this.optType = optType;
        this.optReason = optReason;
        this.marketContext = marketContext;
        this.venID = venID;
        this.vavailability = vavailability;
        this.createdDateTime = createdDateTime;
        this.schemaVersion = schemaVersion;
    }

    /**
     * Gets the value of the optID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptID() {
        return optID;
    }

    /**
     * Sets the value of the optID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptID(String value) {
        this.optID = value;
    }

    /**
     * Gets the value of the optType property.
     * 
     * @return
     *     possible object is
     *     {@link OptTypeType }
     *     
     */
    public OptTypeType getOptType() {
        return optType;
    }

    /**
     * Sets the value of the optType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptTypeType }
     *     
     */
    public void setOptType(OptTypeType value) {
        this.optType = value;
    }

    /**
     * Gets the value of the optReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptReason() {
        return optReason;
    }

    /**
     * Sets the value of the optReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptReason(String value) {
        this.optReason = value;
    }

    /**
     * Gets the value of the marketContext property.
     * 
     * @return
     *     possible object is
     *     {@link MarketContext }
     *     
     */
    public MarketContext getMarketContext() {
        return marketContext;
    }

    /**
     * Sets the value of the marketContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketContext }
     *     
     */
    public void setMarketContext(MarketContext value) {
        this.marketContext = value;
    }

    /**
     * Gets the value of the venID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVenID() {
        return venID;
    }

    /**
     * Sets the value of the venID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVenID(String value) {
        this.venID = value;
    }

    /**
     * Gets the value of the vavailability property.
     * 
     * @return
     *     possible object is
     *     {@link Vavailability }
     *     
     */
    public Vavailability getVavailability() {
        return vavailability;
    }

    /**
     * Sets the value of the vavailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vavailability }
     *     
     */
    public void setVavailability(Vavailability value) {
        this.vavailability = value;
    }

    /**
     * Gets the value of the createdDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getCreatedDateTime() {
        return createdDateTime;
    }

    /**
     * Sets the value of the createdDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setCreatedDateTime(DateTime value) {
        this.createdDateTime = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            String theOptID;
            theOptID = this.getOptID();
            strategy.appendField(locator, this, "optID", buffer, theOptID, (this.optID!= null));
        }
        {
            OptTypeType theOptType;
            theOptType = this.getOptType();
            strategy.appendField(locator, this, "optType", buffer, theOptType, (this.optType!= null));
        }
        {
            String theOptReason;
            theOptReason = this.getOptReason();
            strategy.appendField(locator, this, "optReason", buffer, theOptReason, (this.optReason!= null));
        }
        {
            MarketContext theMarketContext;
            theMarketContext = this.getMarketContext();
            strategy.appendField(locator, this, "marketContext", buffer, theMarketContext, (this.marketContext!= null));
        }
        {
            String theVenID;
            theVenID = this.getVenID();
            strategy.appendField(locator, this, "venID", buffer, theVenID, (this.venID!= null));
        }
        {
            Vavailability theVavailability;
            theVavailability = this.getVavailability();
            strategy.appendField(locator, this, "vavailability", buffer, theVavailability, (this.vavailability!= null));
        }
        {
            DateTime theCreatedDateTime;
            theCreatedDateTime = this.getCreatedDateTime();
            strategy.appendField(locator, this, "createdDateTime", buffer, theCreatedDateTime, (this.createdDateTime!= null));
        }
        {
            String theSchemaVersion;
            theSchemaVersion = this.getSchemaVersion();
            strategy.appendField(locator, this, "schemaVersion", buffer, theSchemaVersion, (this.schemaVersion!= null));
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EiOptType that = ((EiOptType) object);
        {
            String lhsOptID;
            lhsOptID = this.getOptID();
            String rhsOptID;
            rhsOptID = that.getOptID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "optID", lhsOptID), LocatorUtils.property(thatLocator, "optID", rhsOptID), lhsOptID, rhsOptID, (this.optID!= null), (that.optID!= null))) {
                return false;
            }
        }
        {
            OptTypeType lhsOptType;
            lhsOptType = this.getOptType();
            OptTypeType rhsOptType;
            rhsOptType = that.getOptType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "optType", lhsOptType), LocatorUtils.property(thatLocator, "optType", rhsOptType), lhsOptType, rhsOptType, (this.optType!= null), (that.optType!= null))) {
                return false;
            }
        }
        {
            String lhsOptReason;
            lhsOptReason = this.getOptReason();
            String rhsOptReason;
            rhsOptReason = that.getOptReason();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "optReason", lhsOptReason), LocatorUtils.property(thatLocator, "optReason", rhsOptReason), lhsOptReason, rhsOptReason, (this.optReason!= null), (that.optReason!= null))) {
                return false;
            }
        }
        {
            MarketContext lhsMarketContext;
            lhsMarketContext = this.getMarketContext();
            MarketContext rhsMarketContext;
            rhsMarketContext = that.getMarketContext();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "marketContext", lhsMarketContext), LocatorUtils.property(thatLocator, "marketContext", rhsMarketContext), lhsMarketContext, rhsMarketContext, (this.marketContext!= null), (that.marketContext!= null))) {
                return false;
            }
        }
        {
            String lhsVenID;
            lhsVenID = this.getVenID();
            String rhsVenID;
            rhsVenID = that.getVenID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "venID", lhsVenID), LocatorUtils.property(thatLocator, "venID", rhsVenID), lhsVenID, rhsVenID, (this.venID!= null), (that.venID!= null))) {
                return false;
            }
        }
        {
            Vavailability lhsVavailability;
            lhsVavailability = this.getVavailability();
            Vavailability rhsVavailability;
            rhsVavailability = that.getVavailability();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "vavailability", lhsVavailability), LocatorUtils.property(thatLocator, "vavailability", rhsVavailability), lhsVavailability, rhsVavailability, (this.vavailability!= null), (that.vavailability!= null))) {
                return false;
            }
        }
        {
            DateTime lhsCreatedDateTime;
            lhsCreatedDateTime = this.getCreatedDateTime();
            DateTime rhsCreatedDateTime;
            rhsCreatedDateTime = that.getCreatedDateTime();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "createdDateTime", lhsCreatedDateTime), LocatorUtils.property(thatLocator, "createdDateTime", rhsCreatedDateTime), lhsCreatedDateTime, rhsCreatedDateTime, (this.createdDateTime!= null), (that.createdDateTime!= null))) {
                return false;
            }
        }
        {
            String lhsSchemaVersion;
            lhsSchemaVersion = this.getSchemaVersion();
            String rhsSchemaVersion;
            rhsSchemaVersion = that.getSchemaVersion();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "schemaVersion", lhsSchemaVersion), LocatorUtils.property(thatLocator, "schemaVersion", rhsSchemaVersion), lhsSchemaVersion, rhsSchemaVersion, (this.schemaVersion!= null), (that.schemaVersion!= null))) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            String theOptID;
            theOptID = this.getOptID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "optID", theOptID), currentHashCode, theOptID, (this.optID!= null));
        }
        {
            OptTypeType theOptType;
            theOptType = this.getOptType();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "optType", theOptType), currentHashCode, theOptType, (this.optType!= null));
        }
        {
            String theOptReason;
            theOptReason = this.getOptReason();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "optReason", theOptReason), currentHashCode, theOptReason, (this.optReason!= null));
        }
        {
            MarketContext theMarketContext;
            theMarketContext = this.getMarketContext();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "marketContext", theMarketContext), currentHashCode, theMarketContext, (this.marketContext!= null));
        }
        {
            String theVenID;
            theVenID = this.getVenID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "venID", theVenID), currentHashCode, theVenID, (this.venID!= null));
        }
        {
            Vavailability theVavailability;
            theVavailability = this.getVavailability();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "vavailability", theVavailability), currentHashCode, theVavailability, (this.vavailability!= null));
        }
        {
            DateTime theCreatedDateTime;
            theCreatedDateTime = this.getCreatedDateTime();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "createdDateTime", theCreatedDateTime), currentHashCode, theCreatedDateTime, (this.createdDateTime!= null));
        }
        {
            String theSchemaVersion;
            theSchemaVersion = this.getSchemaVersion();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "schemaVersion", theSchemaVersion), currentHashCode, theSchemaVersion, (this.schemaVersion!= null));
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public EiOptType withOptID(String value) {
        setOptID(value);
        return this;
    }

    public EiOptType withOptType(OptTypeType value) {
        setOptType(value);
        return this;
    }

    public EiOptType withOptReason(String value) {
        setOptReason(value);
        return this;
    }

    public EiOptType withMarketContext(MarketContext value) {
        setMarketContext(value);
        return this;
    }

    public EiOptType withVenID(String value) {
        setVenID(value);
        return this;
    }

    public EiOptType withVavailability(Vavailability value) {
        setVavailability(value);
        return this;
    }

    public EiOptType withCreatedDateTime(DateTime value) {
        setCreatedDateTime(value);
        return this;
    }

    public EiOptType withSchemaVersion(String value) {
        setSchemaVersion(value);
        return this;
    }

}
