//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.02 at 04:16:30 PM NZDT 
//


package openadr.model.v20b.ei;

import java.io.Serializable;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import openadr.model.v20b.OadrPayloadResourceStatusType;
import openadr.model.v20b.OadrReportPayloadType;
import openadr.model.v20b.strm.StreamPayloadBase;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Report Payload for use in Reports, snaps, and projections.
 * 
 * <p>Java class for ReportPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportPayloadType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ietf:params:xml:ns:icalendar-2.0:stream}StreamPayloadBaseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}rID"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}confidence" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}accuracy" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}payloadBase"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportPayloadType", propOrder = {
    "rid",
    "confidence",
    "accuracy",
    "payloadBase"
})
@XmlSeeAlso({
    OadrReportPayloadType.class
})
public class ReportPayloadType
    extends StreamPayloadBase
    implements Serializable, Equals2, HashCode2, ToString2
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "rID", required = true)
    protected String rid;
    protected Long confidence;
    protected Float accuracy;
    @XmlElementRef(name = "payloadBase", namespace = "http://docs.oasis-open.org/ns/energyinterop/201110", type = JAXBElement.class)
    protected JAXBElement<? extends PayloadBaseType> payloadBase;

    /**
     * Default no-arg constructor
     * 
     */
    public ReportPayloadType() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public ReportPayloadType(final String rid, final Long confidence, final Float accuracy, final JAXBElement<? extends PayloadBaseType> payloadBase) {
        super();
        this.rid = rid;
        this.confidence = confidence;
        this.accuracy = accuracy;
        this.payloadBase = payloadBase;
    }

    /**
     * A reference to a metadata data point description 
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRID() {
        return rid;
    }

    /**
     * Sets the value of the rid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRID(String value) {
        this.rid = value;
    }

    /**
     * Likely variability of prediction: 0-100
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setConfidence(Long value) {
        this.confidence = value;
    }

    /**
     * Accuracy in same units as interval payload value
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAccuracy() {
        return accuracy;
    }

    /**
     * Sets the value of the accuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAccuracy(Float value) {
        this.accuracy = value;
    }

    /**
     * Gets the value of the payloadBase property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PayloadFloatType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadBaseType }{@code >}
     *     {@link JAXBElement }{@code <}{@link OadrPayloadResourceStatusType }{@code >}
     *     
     */
    public JAXBElement<? extends PayloadBaseType> getPayloadBase() {
        return payloadBase;
    }

    /**
     * Sets the value of the payloadBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PayloadFloatType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PayloadBaseType }{@code >}
     *     {@link JAXBElement }{@code <}{@link OadrPayloadResourceStatusType }{@code >}
     *     
     */
    public void setPayloadBase(JAXBElement<? extends PayloadBaseType> value) {
        this.payloadBase = ((JAXBElement<? extends PayloadBaseType> ) value);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            String theRID;
            theRID = this.getRID();
            strategy.appendField(locator, this, "rid", buffer, theRID, (this.rid!= null));
        }
        {
            Long theConfidence;
            theConfidence = this.getConfidence();
            strategy.appendField(locator, this, "confidence", buffer, theConfidence, (this.confidence!= null));
        }
        {
            Float theAccuracy;
            theAccuracy = this.getAccuracy();
            strategy.appendField(locator, this, "accuracy", buffer, theAccuracy, (this.accuracy!= null));
        }
        {
            JAXBElement<? extends PayloadBaseType> thePayloadBase;
            thePayloadBase = this.getPayloadBase();
            strategy.appendField(locator, this, "payloadBase", buffer, thePayloadBase, (this.payloadBase!= null));
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final ReportPayloadType that = ((ReportPayloadType) object);
        {
            String lhsRID;
            lhsRID = this.getRID();
            String rhsRID;
            rhsRID = that.getRID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "rid", lhsRID), LocatorUtils.property(thatLocator, "rid", rhsRID), lhsRID, rhsRID, (this.rid!= null), (that.rid!= null))) {
                return false;
            }
        }
        {
            Long lhsConfidence;
            lhsConfidence = this.getConfidence();
            Long rhsConfidence;
            rhsConfidence = that.getConfidence();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "confidence", lhsConfidence), LocatorUtils.property(thatLocator, "confidence", rhsConfidence), lhsConfidence, rhsConfidence, (this.confidence!= null), (that.confidence!= null))) {
                return false;
            }
        }
        {
            Float lhsAccuracy;
            lhsAccuracy = this.getAccuracy();
            Float rhsAccuracy;
            rhsAccuracy = that.getAccuracy();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "accuracy", lhsAccuracy), LocatorUtils.property(thatLocator, "accuracy", rhsAccuracy), lhsAccuracy, rhsAccuracy, (this.accuracy!= null), (that.accuracy!= null))) {
                return false;
            }
        }
        {
            JAXBElement<? extends PayloadBaseType> lhsPayloadBase;
            lhsPayloadBase = this.getPayloadBase();
            JAXBElement<? extends PayloadBaseType> rhsPayloadBase;
            rhsPayloadBase = that.getPayloadBase();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "payloadBase", lhsPayloadBase), LocatorUtils.property(thatLocator, "payloadBase", rhsPayloadBase), lhsPayloadBase, rhsPayloadBase, (this.payloadBase!= null), (that.payloadBase!= null))) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            String theRID;
            theRID = this.getRID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "rid", theRID), currentHashCode, theRID, (this.rid!= null));
        }
        {
            Long theConfidence;
            theConfidence = this.getConfidence();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "confidence", theConfidence), currentHashCode, theConfidence, (this.confidence!= null));
        }
        {
            Float theAccuracy;
            theAccuracy = this.getAccuracy();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "accuracy", theAccuracy), currentHashCode, theAccuracy, (this.accuracy!= null));
        }
        {
            JAXBElement<? extends PayloadBaseType> thePayloadBase;
            thePayloadBase = this.getPayloadBase();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "payloadBase", thePayloadBase), currentHashCode, thePayloadBase, (this.payloadBase!= null));
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public ReportPayloadType withRID(String value) {
        setRID(value);
        return this;
    }

    public ReportPayloadType withConfidence(Long value) {
        setConfidence(value);
        return this;
    }

    public ReportPayloadType withAccuracy(Float value) {
        setAccuracy(value);
        return this;
    }

    public ReportPayloadType withPayloadBase(JAXBElement<? extends PayloadBaseType> value) {
        setPayloadBase(value);
        return this;
    }

}
